//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_item
    {
        public long id { get; set; }
        public long item_id { get; set; }
        public long oredr_id { get; set; }
        public int quantity { get; set; }
        public string title { get; set; }
        public int price { get; set; }
        public Nullable<int> total { get; set; }
    
        public virtual item item { get; set; }
        public virtual order order { get; set; }
    }
}
