//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class payday
    {
        public long id { get; set; }
        public Nullable<long> staff_id { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public Nullable<int> hours { get; set; }
        public Nullable<int> SalaryPerHour { get; set; }
        public Nullable<int> total { get; set; }
    
        public virtual staff staff { get; set; }
    }
}
